;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;==========================================================

[colors]
background = #282A2E
background-alt = #373B41
workspace = #2ABDD5
white = #ffffff
foreground = #C5C8C6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880
cpu-background = #1C3EE3
memory-background = #33CC66
wlan-background = #E6F50A

[bar/example]
width = 100%
height = 20pt
radius = 10

; dpi = 96

background = ${colors.background}
foreground = ${colors.white}

line-size = 3pt

border-size = 2pt
border-color = #00000000

padding-left = 2pt
padding-right = 2pt

module-margin = 1

font-0 = Zen-dots;2
font-1 = Iosevka Nerd Font;2
font-2 = Jaini Purva;2
font-3 = "DepartureMono:pixelsize=22;2"

modules-left = xworkspaces 
modules-center = date
modules-right = cpu memory wlan eth volume-down pulseaudio volume-up xkeyboard

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-restack = bspwm

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.workspace}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/pulseaudio]
type = internal/pulseaudio

format = <label-volume>
label-volume = %{A1:pactl set-sink-mute @DEFAULT_SINK@ toggle:}%percentage%%%{A}

[module/volume-up]
type = custom/text
format = <label>
label = 󰝝 
click-left = "pactl set-sink-volume @DEFAULT_SINK@ +5%"

[module/volume-down]
type = custom/text
format = <label>
label = 󰝞 
click-left = "pactl set-sink-volume @DEFAULT_SINK@ -5%"


[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
label = "%{F#ffffff}%{T2}  %{F#ffffff}%percentage_used:2%% %{F-}"
label-background = ${colors.memory-background}
format-prefix = 
format-prefix-foreground = ${colors.memory-background}
format-prefix-font = 4
format-suffix = 
format-suffix-font = 4
format-suffix-foreground = ${colors.memory-background}

;==========================================================

[module/control]
type = custom/text
content = Ctrl
content-background = #D8F6FA
content-foreground = #000000 
content-padding = 3
click-left = ~/Projects/Bash/./control_button.sh

[module/control_shift]
type = custom/text
content = Ctrl+Shift
content-background = #C0FFD0
content-foreground = #000000 
content-padding = 3
click-left = ~/Projects/Bash/./control_shift_button.sh

[module/control_super]
type = custom/text
content = Ctrl+Super
content-background = #F8F0B0
content-foreground = #000000 
content-padding = 3
click-left = ~/Projects/Bash/./control_super_button.sh

[module/control_c]
type = custom/text
content = C-C
content-background = #ED5CA1
content-foreground = #000000 
content-padding = 1
click-left = ~/Projects/Bash/./control_c_button.sh

[module/control_v]
type = custom/text
content = C-V
content-background = #89E619
content-foreground = #000000 
content-padding = 1
click-left = ~/Projects/Bash/./control_v_button.sh
;==========================================================

[module/cpu]
type = internal/cpu
interval = 2
label = "%{F#ffffff}%{T2}  %{F#ffffff}%percentage:2%% %{F-}"
label-background = ${colors.cpu-background}
format-prefix = 
format-prefix-foreground = ${colors.cpu-background}
format-prefix-font = 4
format-suffix = 
format-suffix-font = 4
format-suffix-foreground = ${colors.cpu-background}

;==========================================================

[network-base]
type = internal/network
interval = 5

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#ffffff}%{T2}󰖩 
label-disconnected = %{F#707880}%{T2}󰖪
label = %ifconnected%${label-connected}%else%${label-disconnected}%endif%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#ffffff}󰈀  
label-disconnected = %{F#707880}󰈀  
label = %ifconnected%${label-connected}%else%${label-disconnected}%endif%

;==========================================================

[module/date]
type = internal/date
interval = 1

format-prefix = ""
format-prefix-font = 4
format-prefix-foreground = #ffffff
format-suffix = ""
format-suffix-font = 4
format-suffix-foreground = #ffffff

date = %I : %M %P
date-alt = %Y-%m(%h)-%d(%A)

label = " %date% "
label-font = 2
label-foreground = #000000
label-background = #ffffff

[settings]
screenchange-reload = true
pseudo-transparency = true
